version: '3.8'
services:

  pg:
    image: postgres:14.3-alpine
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: aviasales
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ".data/pg:/var/lib/postgresql/data"

  bot:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - pg
    environment:
      POSTGRES_DB: aviasales
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: pg
      POSTGRES_PORT: 5432
      BOT_TOKEN: ${DOCKER_BOT_TOKEN}
      API_TOKEN: ${DOCKER_API_TOKEN}
      USER_TO_FETCH: ${DOCKER_USER_TO_FETCH}
    restart: unless-stopped
